services:
  addressservice:
    image: ghcr.io/luizgc/homesearch@sha256:7aaa885f3c75a50a311b5b434b10859f15886c91b01b2f3b7668804fee5fdb84
    environment:
      - JDBC_URL=db
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  db:
    image: postgis:3
    build:
      context: .
      dockerfile: dockerfile-postgis
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: homesearch_db
    ports:
      - "5432:5432"
