services:
  db:
    image: postgis:3
    build:
      context: .
      dockerfile: dockerfile-postgis
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: homesearch_db
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: a
      PGADMIN_CONFIG_SERVER_MODE: 'False'
