services:
  addressservice:
    image: ghcr.io/luizgc/homesearch@sha256:ecd4b1ca46c9772db4a67716eaddb74ac4c865b963d55a037d2def9f16d680f5
    environment:
      - JDBC_URL=db
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  db:
    image: postgis:3
    build:
      context: .
      dockerfile: dockerfile-postgis
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: homesearch_db
    ports:
      - "5432:5432"
