services:
  addressservice:
    image: ghcr.io/luizgc/homesearch@sha256:90455d3211774d6f199f2911d4a5f69c2bcae438ce0b19bea9538bf25465ab02
    ports:
      - "7777:8080"
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
  db:
    image: postgis/postgis:17-3.5-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: homesearch_db
